### ISSUE TITLE
"Concat" creates new array

### ISSUE THREAD

**Issue by canonic-epicure** [internalfx/bplus-index#2]
This approach of filling the result array, while being functionally pure, creates unnecessary load on the garbage collector. Since the intermediate "result" values are not used/observed anywhere, would be better to use "push" instead of "concat"

```
result = result.concat(currLoc.leaf.values[currLoc.index])
```

**Comment by internalfx** [comment]
Hi @SamuraiJack,

I stopped development on this library because I created another that proved to be a better solution.

So...

If you are working with a B+Index in JS for study or experimentation, feel free to submit a PR.

If you just want to use a nice fast index library, check out [mindex](https://github.com/internalfx/mindex)

**Comment by canonic-epicure** [comment]
I see. Will check it out, thanks. I noticed you use the same style in mindex btw :)

**Comment by canonic-epicure** [comment]
Just curious what is mindex based on? Skip lists?

**Comment by canonic-epicure** [comment]
Ah, just binary trees? Cool..
